# Basic Information 
title: Nicolas De Ro
position: PhD student
position_fr: Doctorant
affiliation: University of Geneva
affiliation_fr: Université de Genève
email: nicolas.dero (at) unige.ch
private_email: nicolas.deromiralles (at) gmail.com

# Search Engine Optimization (SEO)
keywords: nicolas de ro, nicolas dero, nicolasdero, de ro nicolas, dero nicolas, deronicolas
#canonical: 
description: Nicolas De Ro is a PhD student at the University of Geneva. His research interests include quantum and statistical mechanics, with a focus on condensed matter and many-body physics.

# The option is used to show the last update time.
enable_last_update: true
last_update: Last update
last_update_fr: Dernière mise à jour

# Links
link_type: icon
google_scholar: https://scholar.google.com/citations?user=d-gfkwgAAAAJ&hl=fr
github_link: https://github.com/nicolasdero
orcid: https://orcid.org/0009-0000-7690-1444
linkedin: https://ch.linkedin.com/in/nicolas-de-ro-b8b30635a

# Images 
avatar: /assets/img/avatar.jpeg

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
